### ISSUE TITLE
INSTALL instructions on windows

### ISSUE THREAD

**Issue by dodgyville** [yuce/pyswip#25]
The INSTALL doc says to install on windows:

> Get a Windows installer version of PySWIP and install it.

But I couldn't find a windows installer version anywhere.

This appears to work: Cloning the repo and running:

`py -3 setup.py install `

Is it that simple or should I be worried about something?

Thanks for a great project btw! So great to have Prolog in python.

**Comment by yuce** [comment]
Thanks! The instructions in `INSTALL` are old, I'll be updating those. The "said" Windows installer is here: https://pypi.org/project/pyswip/#files but I'd recommend against installing it, it's very old. I'll be pushing a new release soon.

**Comment by yuce** [comment]
I've uploaded a new version of pyswip to PyPI: https://pypi.org/project/pyswip/ . `pip install pyswip` should work just fine fine now. Updated https://github.com/yuce/pyswip/blob/master/INSTALL.md . There is no Windows installer, since PyPI doesn't let me upload one. But I will try again in the later versions if there's demand.

**Comment by yuce** [comment]
thanks a lot!
