### ISSUE TITLE
Add Android/Termux support

### ISSUE THREAD

**Issue by MitsiCash** [yuce/pyswip#47]
Recently, SWI Prolog added Android support [using Termux](http://www.swi-prolog.org/build/Termux.html) or [using LinuxOnAndroid](http://www.swi-prolog.org/build/linuxonandroid.html). 
Pyswip cannot find the `libswipl` shared library, as it does not search to the appropriate directories. The `libswipl` path should be e.g. for Termux, `$PREFIX/lib/libswipl.so`.

Regards and many thanks,
Theodore

**Comment by yuce** [comment]
Hi Theodore, this is a combination I don't use. But if there is a PR which implements this, we may include it.

**Comment by woofwoof** [comment]
Hello,

I couldn't get pyswip working properly under Android/termux. I think I tried just about everything I could and now seem to have messed everything up so much so that I need to reinstall termux.

It seemed like python was calling swipl but swipl was returning command argument options etc instead of executing the sample Prolog code?

I'd post error messages but as I said I seem to have messed everything up! Things I tired included resetting the file structure to standard using proot (termux-chroot) which overcame the shared library path problem I thought? I did not set up a virtual environment - maybe I should have?

I'll try to repeat my mistakes and be more specific with error message ASAP.

Sorry for the vague post but any ideas may be useful please?

Cheers, WW.

**Comment by MitsiCash** [comment]
It seems that proot solves the library path problem. I have managed to run pyswip on Termux. Here is the complete walkthrough:

- Install python and pyswip:
`pkg install python`
`pip install pyswip`
- Install swipl (see [https://www.swi-prolog.org/build/Termux.html](https://www.swi-prolog.org/build/Termux.html)):
`pkg install curl`
`curl  https://raw.githubusercontent.com/erlanger/swipl-termux/master/install -sSf | sh`
- Install proot (see [https://wiki.termux.com/wiki/Differences_from_Linux#Termux_is_not_FHS_compliant](https://wiki.termux.com/wiki/Differences_from_Linux#Termux_is_not_FHS_compliant)):
`pkg install proot`
- Run proot (every time termux is opened)
`termux-chroot`
- pyswip now works:
`python`
`>>> from pyswip import Prolog`
`>>>`

Cheers,
Theodore

**Comment by woofwoof** [comment]
Hello Theodore,

Could you possibly please tell me what version of Android you're using? I think I pretty much did what your walkthrough indicates but as I have indicated in a new issue the final "from pyswip import Prolog" results in the command line options for swipl being reported to stdin. That said, its great that solution worked for you!

Best, WW.

**Comment by MitsiCash** [comment]
Hello,

I have tested successfully the above on android 6.0 and 7.0. The test on 6.0 was from a clean environment.

Well I don't have any ideas. I see [here](https://github.com/erlanger/swipl-termux/issues/5#issuecomment-533776993) that your swipl is running. So, maybe in addition you can verify that swipl is installed in the right place, by running
`termux-chroot`
and then
`ls /usr/lib | grep swipl`

**Comment by woofwoof** [comment]
Hi.

Thanks. It's not empty. Libswipl.so and swipl directory are there. It seems to me psywip isn't calling swipl correctly since it's returning lots of command line options & then exiting python.

I appreciate your help.

Best, WW.
